dataset_path: amalia-llm/EmbSpatial-Bench-PT
dataset_kwargs:
  token: True
task: "embspatial_pt"
tag:
  - amalia_vl_eval_pt
test_split: test
output_type: generate_until
doc_to_visual: !function utils.embspatial_doc_to_visual
doc_to_text: !function utils.embspatial_doc_to_text
doc_to_target: "answer"

process_results: !function utils.embspatial_process_results

metric_list:
  - metric: embspatial_acc
    aggregation: !function utils.embspatial_aggregate_results
    higher_is_better: true
  - metric: ai2thor_accuracy
    aggregation: !function utils.embspatial_aggregate_ai2thor_accuracy
    higher_is_better: true
  - metric: mp3d_accuracy
    aggregation: !function utils.embspatial_aggregate_mp3d_accuracy
    higher_is_better: true
  - metric: scannet_accuracy
    aggregation: !function utils.embspatial_aggregate_scannet_accuracy
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: "Nota: Apenas necessita de responder com A, B, C, D sem fornecer qualquer informação adicional.\n"
    post_prompt: ""

generation_kwargs:
  max_new_tokens: 1024

metadata:
  - version: 0.0
